# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/xujiahua/alertmanager-webhook-feishu/cmd.version={{.Version}} -X github.com/xujiahua/alertmanager-webhook-feishu/cmd.commit={{.Commit}} -X github.com/xujiahua/alertmanager-webhook-feishu/cmd.date={{.Date}} -X github.com/xujiahua/alertmanager-webhook-feishu/cmd.builtBy=goreleaser
    goos:
      - linux
      - windows
      - darwin
dockers:
  -
    # GOOS of the built binaries/packages that should be used.
    goos: linux
    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64
    # Templates of the Docker image names.
    image_templates:
      - "johnxu1989/alertmanager-webhook-feishu:latest"
      - "johnxu1989/alertmanager-webhook-feishu:{{ .Tag }}"

    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile.goreleaser

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
