apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager-webhook-feishu.fullname" . }}
  labels:
    {{- include "alertmanager-webhook-feishu.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
